BdeBInterfaceContracts/Controllers/OrdersController.cs
using BdeBInterfaceContracts.Models;
using BdeBInterfaceContracts.Repositories;
using System.Web.Mvc;
using BdeBInterfaceContracts.Services;

namespace BdeBInterfaceContracts.Controllers
{
	public class OrdersController : Controller
	{
		public ActionResult Index(OrderBy orderBy = OrderBy.None)
		{
			var orderRepository = new OrderRepository();

            #region EX 2.0 (Sprint 2)

            // EX 2.0
            // Notre client nous demande cette fois-ci d'implémenter les mêmes
            // tris que pour les produits. Facile!
            // Hmmm... Il va falloir faire quelques changements, mais on peut
            // commencer par ajouter le même code que celui qu'on trouve dans
            // le ProductsController. Idéalement, on va aussi changer les noms
            // de variables pour mieux représenter le domaine avec lequel on
            // travaille dans ce contrôleur.
            // Mais il y a quelque chose qui cloche : C# nous donne à nouveau
            // la même erreur obscure que plus tôt, en nous disant qu'il est
            // impossible de convertir un Order en INameable ou IHasCreateDate.
            // Il va falloir encore une fois aller ajouter les interfaces
            // à la classe Order, pour que C# comprenne qu'elles implémentent
            // le contrat qui est défini par ces deux interfaces!
            // Allons à EX 2.1.

            // -----------------------------------------------------------------
            // EX 2.3 (au retour)
            // C# est content, maintenant!
            // C'est le temps de tester que tout fonctionne en lançant
            // l'application!

            #endregion

            return View(orderRepository);
        }
	}
}

BdeBInterfaceContracts/Controllers/ProductsController.cs
using BdeBInterfaceContracts.Models;
using BdeBInterfaceContracts.Repositories;
using BdeBInterfaceContracts.Services;
using System.Web.Mvc;

namespace BdeBInterfaceContracts.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index(OrderBy orderBy = OrderBy.None)
        {
            var productRepository = new ProductRepository();

            if (orderBy == OrderBy.Name)
            {
                var sortingService = new SortingService();
                var orderedProducts = sortingService.OrderByName(productRepository);
                return View(orderedProducts);
            }
            #region EX 1.3

            // EX 1.3
            // Il est temps d'appeler notre nouvelle méthode!
            // Ajoutons un else if qui sera contre OrderBy.CreationDateDesc.
            // On peut copier le code d'en haut et faire les changements requis.
            // À part la condition du if, il faut simplement changer le nom de
            // la méthode pour celle que l'on vient de créer.
            // Hmmm, encore une erreur de C#, un peu plus obscure, cette
            // fois-ci. C# nous dit qu'il est impossible de traiter un Product
            // comme un IHasCreateDate...
            // En effet, en C#, il faut toujours indiquer explicitement qu'une
            // classe implémente une interface! Même si la classe a déjà les
            // propriétés requises, C# attend de nous qu'on lui confirme
            // qu'un contrat existe bien!
            // Allons à EX 1.4!

            // -----------------------------------------------------------------
            // EX 1.5 (au retour)
            // Et voilà, tout marche, maintenant!
            // Il est temps de tester l'application!

            #endregion

            return View(productRepository);
        }
    }
}

BdeBInterfaceContracts/Controllers/UserRolesController.cs
using BdeBInterfaceContracts.Repositories;
using System.Web.Mvc;

namespace BdeBInterfaceContracts.Controllers
{
	public class UserRolesController : Controller
	{
		public ActionResult Index()
		{
			var userRoles = new UserRoleRepository();
			return View(userRoles);
		}
	}
}

BdeBInterfaceContracts/Controllers/UsersController.cs
using BdeBInterfaceContracts.Models;
using BdeBInterfaceContracts.Repositories;
using System.Web.Mvc;
using BdeBInterfaceContracts.Services;

namespace BdeBInterfaceContracts.Controllers
{
	public class UsersController : Controller
	{
		public ActionResult Index(OrderBy orderBy = OrderBy.None)
		{
			var userRepository = new UserRepository();

            #region EX 3.0 (Sprint 2)

            // EX 3.0
            // Dans ce sprint, notre client nous a demandé de compléter la
            // fonctionnalité de tri en l'ajoutant aux Orders et aux Users.
            // Nous avons vu comment faire pour l'ajouter aux Orders, c'est
            // maintenant à vous de jouer pour les Users!
            // Appliquez tout ce que nous avons vu jusqu'à présent pour
            // implémenter la dernière fonctionnalité de ce sprint!

            #endregion

            return View(userRepository);
		}
	}
}

BdeBInterfaceContracts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Présentation des contrats d'interfaces</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button> 
			</div>
			<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Produits", "Index", "Products")</li>
                    <li>@Html.ActionLink("Commandes", "Index", "Orders")</li>
                    <li>@Html.ActionLink("Utilisateurs", "Index", "Users")</li>
                    <li>@Html.ActionLink("Rôles", "Index", "UserRoles")</li>
                </ul>
			</div>
		</div>
	</div>

	<div class="container body-content">
		@RenderBody()
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>